### ISSUE TITLE
Contribution process

### ISSUE THREAD

**Issue by tarekmansour** [wgnf/dotnet-nuget-licenses#21]
Hello Martin,

I want to contribute to your project, but I cannot find any contribution process to follow.

Or I could help you directly on opened issues?

**Comment by wgnf** [comment]
Hey Tarek,

Thanks for reaching out. Because this project is not nearly finished and I'm just working on it on and off when I have time for it, I didn't see the need to provide any documentation for now. I guess I was wrong :D

As long as I haven't added any documentation about this in this project, you could follow the Contributing Guidelines that I have set up [here](https://github.com/wgnf/SlnParser#-want-to-contribute)

Looking forward to your contributions :)

**Comment by wgnf** [comment]
Basically what you can do to contribute is:

- file bugs (i guess that is not an option for now)
- let me know about features that you want to see
- engage in discussions (either [Discussions](https://github.com/wgnf/dotnet-nuget-licenses/discussions) directly or in the [Issues](https://github.com/wgnf/dotnet-nuget-licenses/issues)
- When you have an Issue that you want to work on, fork the project (what you already did), open up a branch, work on it, and then open a Pull Request in this project, so that I can have a look at it)

**Comment by wgnf** [comment]
I've updated the [README](https://github.com/wgnf/dotnet-nuget-licenses/blob/main/README.md) and added [Contributing-Guidelines](https://github.com/wgnf/dotnet-nuget-licenses/blob/main/CONTRIBUTING.md).  
  
As there's no more work to be done here, but there might still be questions or other ideas, I'll turn this into a discussion.
